### ISSUE TITLE
Plaits oscillator

### ISSUE THREAD

**Issue by flocked** [laamaa/TeensySynth_mk2#1]
Would it be possible to use the Plaits oscillator in a further version of it or do Plaits oscillator need too much performance?

**Comment by laamaa** [comment]
Sounds interesting! I need to try and see if I could get it running on the Teensy.

**Comment by laamaa** [comment]
Thanks for the idea. It seems to work with Teensy pretty nicely, needs still some testing how many oscillators can be run simultaneously though. I think I'll scrap this project for now and make a new one using Plaits as a base instead :)
